dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)

    repositories {
        google()
        mavenCentral()
        maven { url "https://maven.transistorsoft.com" }
    }
}

rootProject.name = "android"

include ':app'
apply from: 'capacitor.settings.gradle'
