// ✅ src/components/SolarGraph.jsx
import React from "react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Legend,
} from "recharts";

/**
 * SolarGraph.jsx
 * ------------------------------------------------------------
 * Shows savings comparison (Before Solar vs After Solar)
 * using company theme (Maroon / Gold / White)
 * ------------------------------------------------------------
 */
const SolarGraph = ({
  yearlyConsumption = 30000, // Annual units consumed before solar
  solarGeneration = 1825,    // Units generated by solar per kW
  pricePerUnit = 6.3,        // Electricity rate (₹/unit)
  yearlyIncrement = 2,       // % increase in grid power cost per year
  yearlyDecrement = 0.4,     // % degradation of solar output per year
  years = 10,                // Graph span (years)
}) => {
  const maroon = "#800000";
  const gold = "#D4AF37";
  const lightBg = "#f8f1ef";

  /* 🔹 Calculate year-wise values */
  const data = [];
  let gridCost = yearlyConsumption * pricePerUnit;
  let solarCost = (yearlyConsumption - solarGeneration) * pricePerUnit;

  for (let year = 1; year <= years; year++) {
    data.push({
      year: `Year ${year}`,
      "Before Solar (₹)": Math.round(gridCost),
      "After Solar (₹)": Math.round(solarCost),
    });

    gridCost += (gridCost * yearlyIncrement) / 100;
    solarCost +=
      (solarCost * yearlyIncrement) / 100 -
      (solarCost * yearlyDecrement) / 100;
  }

  return (
    <div
      style={{
        width: "100%",
        height: "100%",
        background: lightBg,
        borderRadius: "12px",
        padding: "20px",
        boxSizing: "border-box",
      }}
    >
      <ResponsiveContainer width="100%" height={300}>
        <BarChart
          data={data}
          margin={{ top: 20, right: 30, left: 0, bottom: 5 }}
          barCategoryGap="20%"
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#e2c8c8" />
          <XAxis dataKey="year" tick={{ fill: maroon, fontWeight: 600 }} />
          <YAxis
            tick={{ fill: maroon }}
            tickFormatter={(v) => `₹${(v / 1000).toFixed(0)}k`}
          />
          <Tooltip
            contentStyle={{
              backgroundColor: "#fff",
              border: `1px solid ${maroon}`,
              borderRadius: "6px",
            }}
            formatter={(value) => [`₹${value.toLocaleString()}`, "Cost"]}
          />
          <Legend
            verticalAlign="top"
            height={36}
            wrapperStyle={{ color: maroon, fontWeight: 600 }}
          />
          <Bar
            dataKey="Before Solar (₹)"
            fill={maroon}
            radius={[8, 8, 0, 0]}
            barSize={22}
          />
          <Bar
            dataKey="After Solar (₹)"
            fill={gold}
            radius={[8, 8, 0, 0]}
            barSize={22}
          />
        </BarChart>
      </ResponsiveContainer>

      <p
        style={{
          textAlign: "center",
          color: maroon,
          fontSize: "14px",
          marginTop: "8px",
        }}
      >
        *Estimated yearly power cost reduction after solar installation
      </p>
    </div>
  );
};

export default SolarGraph;
